create table rescue_centers(
    id  bigint generated by default as identity primary key,
    code varchar(20) not null, 
    name varchar(100) not null, 
    city varchar (100) not null,

    constraint uk_rescue_centers_code unique (code)



);

create table rescue_cases(
    id bigint generated by default as identity primary key,
    case_code varchar(50) not null,
    rescue_date date,
    rescue_location varchar(300),
    status varchar(30), 
    rescue_center_id bigint, 

    constraint uk_rescue_cases_case_code unique (case_code),
    constraint fk_rescue_cases_rescue_center foreign key (rescue_center_id) references rescue_centers(id),
    constraint chk_rescue_cases_status check (status in ('ADMITTED', 'UNDER_EVALUATION','IN_REHABILITATION', 'READY_FOR_RELEASE', 'RELEASED', 'CLOSED'))
);

create table animals (
    id bigint generated by default as identity primary key,
    animal_code varchar(50) not null,
    common_name varchar(150),
    scientific_name varchar(200),
    sex varchar(10),
    rescue_case_id bigint,

    constraint uk_animals_animal_code unique (animal_code),
    constraint uk_animals_rescue_case_id unique (rescue_case_id),
    constraint fk_animals_rescue_case_id foreign key (rescue_case_id) references rescue_cases(id)
);

create table medical_records(
    id bigint generated by default as identity primary key,
    animal_id bigint not null,
    initial_weight numeric(6, 2),
    initial_condition text not null,
    injuries text,
    observations text,

    constraint uk_medical_records_animal unique (animal_id),
    constraint fk_medical_records_animal foreign key(animal_id) references animals(id)

);

create table specialists (
    id bigint generated by default as identity primary key,
    professional_code varchar(30) not null,
    first_name varchar(100) not null,
    last_name varchar(100) not null, 
    email varchar(100) not null,
    active boolean not null default true,

    constraint uk_specialists_professional_code unique (professional_code),
    constraint uk_specialists_email unique (email)

);

create table expertise(
    id bigint generated by default as identity primary key,
    name varchar(100) not null,

    constraint uk_expertise_name unique (name)
);

create table specialist_expertise(
    specialist_id bigint not null,
    expertise_id bigint not null,

    constraint pk_specialist_expertise primary key (specialist_id, expertise_id),
    constraint fk_specialist_expertise_specialist foreign key (specialist_id) references specialists(id),
    constraint fk_specialist_expertise_expertise foreign key (expertise_id) references expertise(id)

);

create table treatments (
    id bigint generated by default as identity primary key,
    animal_id bigint not null,
    specialist_id bigint,
    performed_at timestamp,
    type varchar(100),
    description text,

    constraint fk_treatments_animal foreign key (animal_id) references animals(id),
    constraint fk_treatments_specialist foreign key (specialist_id) references specialists(id)
);

create index idx_rescue_cases_rescue_center_id on rescue_cases(rescue_center_id);
create index idx_rescue_cases_status on rescue_cases(status);
create index idx_rescue_cases_rescue_date on rescue_cases(rescue_date);
create index idx_treatments_animal_id on treatments(animal_id);
create index idx_treatments_specialist_id on treatments(specialist_id);
create index idx_treatments_performed_at on treatments(performed_at);